### ISSUE TITLE
Refactor the way options are stored

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/page-for-post-types#4]
Right now, the data for this plugin is stored in individual options that all share a common guid prefix so that we can delete them on the plugin delete action.

In order to simplify things, we're going to store the option keys as an array so that we can forgo the guid prefix and so that users can fetch the pages with the WordPress function `get_option` rather than a custom function. Users should be able to get the page for a post type named "book" using `get_option( 'page_for_book' );`

Still debating whether we want to pluralize that or just leave it based on the post type name.

**Comment by gwelser** [comment]
Addressed in pull request #6
