### ISSUE TITLE
Rewrite has double domain in URL

### ISSUE THREAD

**Issue by huubl** [Clark-Nikdel-Powell/page-for-post-types#8]
Hi,

I get https://www.domain.nl/https://www.domain.nl/case-studies/test/ as URL for single posts. Do you know what's causing this?

**Comment by jhned** [comment]
Hi, thanks for opening this issue. Let's do some basic triage so that we can reproduce your issue:

1. Is this for the built-in "Post" post type, or for a custom post type? If for a custom post type, please share your args for `register_post_type`, as well as any `register_taxonomy` args for the post type.
1. Try flushing the rewrite rules by visiting Settings -> Permalinks in the WordPress admin. Does the issue persist?
1. Does the issue persist if you have all other plugins deactivated, and switched to the default WordPress theme?

**Comment by huubl** [comment]
Hi,

Thanks for helping.

**Is this for the built-in "Post" post type, or for a custom post type? If for a custom post type, please share your args for register_post_type, as well as any register_taxonomy args for the post type.**

It's a custom post-type:

```
    register_post_type('verhalen',
        array(
            'labels' => array(
                'name' => __('Verhalen', 'smdzr'),
                'singular_name' => __('Verhalen', 'smdzr'),
            ),
            'public' => true,
            'publicly_queryable' => true,
            'exclude_from_search' => false,
            'show_ui' => true,
            'show_in_menu' => true,
            'menu_position' => 20,
            'delete_with_user' => false,
            'show_in_rest' => true,
            'rest_base' => '',
            'menu_icon' => 'dashicons-groups',
            'supports' => array(
                'title', 'editor', 'revisions', 'thumbnail', 'page-attributes', 'custom-fields',  'dashicons-groups'),
            'taxonomies' => array( 'post_tag', 'category'),
            'rest_controller_class' => 'WP_REST_Posts_Controller',
            'has_archive' => false,
            'show_in_nav_menus' => true,
            'capability_type' => 'post',
            'map_meta_cap' => true,
            'hierarchical' => false,
            'rewrite' => array(
                'slug' => 'verhalen',
                'with_front' => false ),
            'query_var' => true,
            //https://github.com/Clark-Nikdel-Powell/page-for-post-types
            'has_post_type_page' => true,
        )
    );
```

**Try flushing the rewrite rules by visiting Settings -> Permalinks in the WordPress admin. Does the issue persist**

Yes, no difference unfortunately.

**Does the issue persist if you have all other plugins deactivated, and switched to the default WordPress theme?**

Yes, the issue still persists with only the Twenty Twenty theme and all other plugins deactivated.

I use Bedrock (https://roots.io/bedrock/) as base for Wordpress.

**Comment by jhned** [comment]
Thanks for the info, I'll take a look now.

**Comment by jhned** [comment]
Well, I see one thing that seems out of place-- `'has_archive'` is set to `false`. The point of this plugin is to give you a place to enter in content for a post type archive. Did you mean to have `has_archive` set to false? I haven't reproduced the specific issue you're having yet. Here's what I've tried:

1. Fresh install of WordPress
2. Install Page for Post Types from Github
3. Set up plugin for your post type args
4. Add a "Case Studies" page and two Verhalen posts.
5. Set "Case Studies" as the page for Verhalen posts in Reading settings
6. Rebuilt permalinks
7. Changed `has_archive` to `true`.
8. Case study archive content is available at http://sandbox.test/case-studies/.
9. Case studies singular post is available at: http://sandbox.test/case-studies/case-study-1/.

Look at includes/class-page-for-post-types-shared.php, line 200 at the `get_rewrite_slug` function. It sounds like something's going wrong with that search-replace. If you'd like us to continue debugging this, please send us access to your project repo.

**Comment by huubl** [comment]
> Well, I see one thing that seems out of place-- `'has_archive'` is set to `false`. The point of this plugin is to give you a place to enter in content for a post type archive. Did you mean to have `has_archive` set to false?

No, I changed it to test if it made a difference. I forget to change it back to false :)

When I change site_url() to home_url() at https://github.com/Clark-Nikdel-Powell/page-for-post-types/blob/195fd58f6bb76af34903206edb5c46f29c1cbbef/includes/class-page-for-post-types-shared.php#L203 everything works as expected.

When using [Bedrock ](https://github.com/roots/bedrock) site_url() returns /wp, is it possible to make a filter or replace it with home_url()?
